import ModulePage from "../../components/ModulePage";
export default function Page(){return <ModulePage eyebrow="FINANCIAL CONTROL" title="Accounting" description="Review chart-of-account balances and ledger movements generated by lending operations." metrics={[{value:"Balanced",label:"Ledger status"},{value:"24",label:"Ledger accounts"},{value:"1,291",label:"Journals this month"}]} columns={["Account","Type","Debit","Credit","Net balance","Status"]} rows={[
 {cells:["1100 · Loan receivables","Asset","K 1,311,200","K 26,700","K 1,284,500"],status:{label:"Active",tone:"green"}},
 {cells:["4100 · Interest income","Income","K 0","K 96,440","K 96,440"],status:{label:"Active",tone:"green"}},
 {cells:["1000 · Cash & bank","Asset","K 812,440","K 524,000","K 288,440"],status:{label:"Active",tone:"green"}},
 {cells:["4200 · Fee income","Income","K 0","K 18,250","K 18,250"],status:{label:"Active",tone:"green"}}
 ]}/>}
