-- ABC Loan Management
-- Migration 001: multi-tenant lending core
-- Oracle Database 19c+ compatible design

CREATE TABLE organisations (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR2(36) NOT NULL UNIQUE,
  legal_name VARCHAR2(200) NOT NULL,
  trading_name VARCHAR2(200),
  registration_number VARCHAR2(100),
  country_code CHAR(2) DEFAULT 'ZM' NOT NULL,
  base_currency CHAR(3) DEFAULT 'ZMW' NOT NULL,
  timezone VARCHAR2(64) DEFAULT 'Africa/Lusaka' NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
    CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','CLOSED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE branches (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  name VARCHAR2(150) NOT NULL,
  code VARCHAR2(50) NOT NULL,
  phone VARCHAR2(30),
  address_line VARCHAR2(250),
  town VARCHAR2(100),
  province VARCHAR2(100),
  active NUMBER(1) DEFAULT 1 NOT NULL CHECK (active IN (0,1)),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_branch_code UNIQUE (organisation_id, code)
);

CREATE TABLE app_users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR2(36) NOT NULL UNIQUE,
  email VARCHAR2(320) NOT NULL,
  phone VARCHAR2(30),
  password_hash VARCHAR2(255) NOT NULL,
  first_name VARCHAR2(100) NOT NULL,
  last_name VARCHAR2(100) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
    CHECK (status IN ('PENDING','ACTIVE','LOCKED','DISABLED')),
  email_verified_at TIMESTAMP WITH TIME ZONE,
  phone_verified_at TIMESTAMP WITH TIME ZONE,
  last_login_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE roles (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR2(60) NOT NULL UNIQUE,
  name VARCHAR2(100) NOT NULL,
  description VARCHAR2(500)
);

CREATE TABLE organisation_memberships (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  user_id NUMBER NOT NULL REFERENCES app_users(id),
  branch_id NUMBER REFERENCES branches(id),
  role_id NUMBER NOT NULL REFERENCES roles(id),
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
    CHECK (status IN ('INVITED','ACTIVE','SUSPENDED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_org_user_role UNIQUE (organisation_id, user_id, role_id)
);

CREATE TABLE borrowers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR2(36) NOT NULL UNIQUE,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  user_id NUMBER REFERENCES app_users(id),
  borrower_type VARCHAR2(20) NOT NULL CHECK (borrower_type IN ('INDIVIDUAL','BUSINESS')),
  display_name VARCHAR2(200) NOT NULL,
  phone VARCHAR2(30),
  email VARCHAR2(320),
  country_code CHAR(2) DEFAULT 'ZM' NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
    CHECK (status IN ('PROSPECT','ACTIVE','BLOCKED','CLOSED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_borrowers_org ON borrowers(organisation_id);

CREATE TABLE individual_borrowers (
  borrower_id NUMBER PRIMARY KEY REFERENCES borrowers(id),
  first_name VARCHAR2(100) NOT NULL,
  last_name VARCHAR2(100) NOT NULL,
  date_of_birth DATE,
  national_id_type VARCHAR2(30),
  national_id_number VARCHAR2(100),
  employment_status VARCHAR2(50),
  employer_name VARCHAR2(200),
  monthly_income NUMBER(19,4),
  CONSTRAINT ck_ind_income CHECK (monthly_income IS NULL OR monthly_income >= 0)
);

CREATE TABLE business_borrowers (
  borrower_id NUMBER PRIMARY KEY REFERENCES borrowers(id),
  legal_name VARCHAR2(200) NOT NULL,
  registration_number VARCHAR2(100),
  tax_number VARCHAR2(100),
  industry VARCHAR2(120),
  annual_revenue NUMBER(19,4),
  contact_person VARCHAR2(200),
  CONSTRAINT ck_business_revenue CHECK (annual_revenue IS NULL OR annual_revenue >= 0)
);

CREATE TABLE loan_products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR2(36) NOT NULL UNIQUE,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  name VARCHAR2(150) NOT NULL,
  code VARCHAR2(50) NOT NULL,
  currency CHAR(3) DEFAULT 'ZMW' NOT NULL,
  interest_method VARCHAR2(30) NOT NULL
    CHECK (interest_method IN ('FLAT','REDUCING_BALANCE')),
  annual_interest_rate NUMBER(9,6) NOT NULL CHECK (annual_interest_rate >= 0),
  min_principal NUMBER(19,4) NOT NULL CHECK (min_principal >= 0),
  max_principal NUMBER(19,4) NOT NULL CHECK (max_principal >= min_principal),
  min_term NUMBER(6) NOT NULL CHECK (min_term > 0),
  max_term NUMBER(6) NOT NULL CHECK (max_term >= min_term),
  term_unit VARCHAR2(20) NOT NULL CHECK (term_unit IN ('DAYS','WEEKS','MONTHS','YEARS')),
  repayment_frequency VARCHAR2(20) NOT NULL
    CHECK (repayment_frequency IN ('DAILY','WEEKLY','BIWEEKLY','MONTHLY','QUARTERLY','CUSTOM')),
  collateral_policy VARCHAR2(20) DEFAULT 'OPTIONAL' NOT NULL
    CHECK (collateral_policy IN ('NONE','OPTIONAL','REQUIRED')),
  guarantor_policy VARCHAR2(20) DEFAULT 'OPTIONAL' NOT NULL
    CHECK (guarantor_policy IN ('NONE','OPTIONAL','REQUIRED')),
  active NUMBER(1) DEFAULT 1 NOT NULL CHECK (active IN (0,1)),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_product_code UNIQUE (organisation_id, code)
);

CREATE TABLE loan_applications (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR2(36) NOT NULL UNIQUE,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  borrower_id NUMBER NOT NULL REFERENCES borrowers(id),
  product_id NUMBER NOT NULL REFERENCES loan_products(id),
  requested_principal NUMBER(19,4) NOT NULL CHECK (requested_principal > 0),
  requested_term NUMBER(6) NOT NULL CHECK (requested_term > 0),
  purpose VARCHAR2(1000),
  status VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL
    CHECK (status IN ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','WITHDRAWN','EXPIRED')),
  submitted_at TIMESTAMP WITH TIME ZONE,
  decided_at TIMESTAMP WITH TIME ZONE,
  decided_by NUMBER REFERENCES app_users(id),
  decision_notes VARCHAR2(2000),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_applications_org_status ON loan_applications(organisation_id, status);

CREATE TABLE guarantors (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id NUMBER NOT NULL REFERENCES loan_applications(id),
  full_name VARCHAR2(200) NOT NULL,
  phone VARCHAR2(30),
  national_id_number VARCHAR2(100),
  relationship VARCHAR2(100),
  guaranteed_amount NUMBER(19,4),
  consent_at TIMESTAMP WITH TIME ZONE,
  CHECK (guaranteed_amount IS NULL OR guaranteed_amount >= 0)
);

CREATE TABLE collateral (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id NUMBER NOT NULL REFERENCES loan_applications(id),
  collateral_type VARCHAR2(100) NOT NULL,
  description VARCHAR2(1000) NOT NULL,
  estimated_value NUMBER(19,4) NOT NULL CHECK (estimated_value >= 0),
  ownership_reference VARCHAR2(250),
  verification_status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
    CHECK (verification_status IN ('PENDING','VERIFIED','REJECTED')),
  verified_by NUMBER REFERENCES app_users(id),
  verified_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE loans (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR2(36) NOT NULL UNIQUE,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  application_id NUMBER NOT NULL UNIQUE REFERENCES loan_applications(id),
  borrower_id NUMBER NOT NULL REFERENCES borrowers(id),
  product_id NUMBER NOT NULL REFERENCES loan_products(id),
  account_number VARCHAR2(80) NOT NULL,
  currency CHAR(3) NOT NULL,
  principal NUMBER(19,4) NOT NULL CHECK (principal > 0),
  annual_interest_rate NUMBER(9,6) NOT NULL CHECK (annual_interest_rate >= 0),
  interest_method VARCHAR2(30) NOT NULL CHECK (interest_method IN ('FLAT','REDUCING_BALANCE')),
  disbursement_date DATE,
  maturity_date DATE,
  status VARCHAR2(30) DEFAULT 'APPROVED' NOT NULL
    CHECK (status IN ('APPROVED','ACTIVE','IN_ARREARS','RESTRUCTURED','PAID_OFF','WRITTEN_OFF','CANCELLED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_loan_account UNIQUE (organisation_id, account_number)
);

CREATE INDEX ix_loans_org_status ON loans(organisation_id, status);

CREATE TABLE repayment_schedule (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id NUMBER NOT NULL REFERENCES loans(id),
  instalment_number NUMBER(6) NOT NULL,
  due_date DATE NOT NULL,
  principal_due NUMBER(19,4) DEFAULT 0 NOT NULL CHECK (principal_due >= 0),
  interest_due NUMBER(19,4) DEFAULT 0 NOT NULL CHECK (interest_due >= 0),
  fees_due NUMBER(19,4) DEFAULT 0 NOT NULL CHECK (fees_due >= 0),
  amount_paid NUMBER(19,4) DEFAULT 0 NOT NULL CHECK (amount_paid >= 0),
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
    CHECK (status IN ('PENDING','PARTIAL','PAID','OVERDUE','WAIVED')),
  CONSTRAINT uq_loan_instalment UNIQUE (loan_id, instalment_number)
);

CREATE TABLE ledger_accounts (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  code VARCHAR2(40) NOT NULL,
  name VARCHAR2(150) NOT NULL,
  account_type VARCHAR2(20) NOT NULL
    CHECK (account_type IN ('ASSET','LIABILITY','EQUITY','INCOME','EXPENSE')),
  active NUMBER(1) DEFAULT 1 NOT NULL CHECK (active IN (0,1)),
  CONSTRAINT uq_ledger_account UNIQUE (organisation_id, code)
);

CREATE TABLE journals (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR2(36) NOT NULL UNIQUE,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  loan_id NUMBER REFERENCES loans(id),
  reference_type VARCHAR2(40) NOT NULL,
  reference_id VARCHAR2(100),
  description VARCHAR2(500) NOT NULL,
  posted_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  reversal_of_journal_id NUMBER REFERENCES journals(id),
  created_by NUMBER REFERENCES app_users(id)
);

CREATE TABLE ledger_entries (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_id NUMBER NOT NULL REFERENCES journals(id),
  account_id NUMBER NOT NULL REFERENCES ledger_accounts(id),
  debit NUMBER(19,4) DEFAULT 0 NOT NULL CHECK (debit >= 0),
  credit NUMBER(19,4) DEFAULT 0 NOT NULL CHECK (credit >= 0),
  currency CHAR(3) NOT NULL,
  CONSTRAINT ck_one_sided_entry CHECK (
    (debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)
  )
);

CREATE INDEX ix_ledger_entries_journal ON ledger_entries(journal_id);

CREATE TABLE payments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR2(36) NOT NULL UNIQUE,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  loan_id NUMBER NOT NULL REFERENCES loans(id),
  amount NUMBER(19,4) NOT NULL CHECK (amount > 0),
  currency CHAR(3) NOT NULL,
  method VARCHAR2(30) NOT NULL
    CHECK (method IN ('CASH','BANK_TRANSFER','CARD','MTN_MOMO','AIRTEL_MONEY','ZAMTEL_MONEY','OTHER')),
  provider_reference VARCHAR2(150),
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
    CHECK (status IN ('PENDING','COMPLETED','FAILED','REVERSED')),
  received_at TIMESTAMP WITH TIME ZONE,
  journal_id NUMBER REFERENCES journals(id),
  recorded_by NUMBER REFERENCES app_users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE collection_cases (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organisation_id NUMBER NOT NULL REFERENCES organisations(id),
  loan_id NUMBER NOT NULL REFERENCES loans(id),
  status VARCHAR2(30) DEFAULT 'OPEN' NOT NULL
    CHECK (status IN ('OPEN','PROMISE_TO_PAY','HARDSHIP','ESCALATED','RESOLVED','CLOSED')),
  days_past_due NUMBER(8) DEFAULT 0 NOT NULL CHECK (days_past_due >= 0),
  amount_overdue NUMBER(19,4) DEFAULT 0 NOT NULL CHECK (amount_overdue >= 0),
  assigned_to NUMBER REFERENCES app_users(id),
  next_action_at TIMESTAMP WITH TIME ZONE,
  notes VARCHAR2(2000),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE audit_events (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organisation_id NUMBER REFERENCES organisations(id),
  actor_user_id NUMBER REFERENCES app_users(id),
  event_type VARCHAR2(100) NOT NULL,
  entity_type VARCHAR2(100) NOT NULL,
  entity_public_id VARCHAR2(100),
  ip_address VARCHAR2(64),
  metadata CLOB CHECK (metadata IS JSON),
  occurred_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO roles(code, name, description) VALUES ('PLATFORM_ADMIN','Platform Administrator','EJ Businesses platform administration');
INSERT INTO roles(code, name, description) VALUES ('ORG_OWNER','Organisation Owner','Full tenant administration');
INSERT INTO roles(code, name, description) VALUES ('MANAGER','Manager','Operational lender management');
INSERT INTO roles(code, name, description) VALUES ('LOAN_OFFICER','Loan Officer','Borrower and loan operations');
INSERT INTO roles(code, name, description) VALUES ('CASHIER','Cashier','Payment recording and reconciliation');
INSERT INTO roles(code, name, description) VALUES ('COLLECTIONS','Collections Officer','Arrears and recovery workflows');
INSERT INTO roles(code, name, description) VALUES ('AUDITOR','Auditor','Read-only financial and audit access');

COMMIT;
