"use client";
import AppShell from "../../../components/AppShell"; import PageHeader from "../../../components/PageHeader"; import {Save} from "lucide-react"; import {useState} from "react";
export default function Page(){
 const [method,setMethod]=useState("REDUCING_BALANCE");
 return <AppShell><div className="content"><PageHeader eyebrow="PRODUCT BUILDER" title="Create loan product" description="Configure the financial rules that will be snapshotted onto originated loans." action={<button className="primary"><Save size={17}/> Save draft</button>}/>
  <div className="builder-layout"><aside className="card builder-steps"><b>Product setup</b><a className="active">1 · General</a><a>2 · Terms & pricing</a><a>3 · Repayment</a><a>4 · Risk controls</a><a>5 · Accounting</a><a>6 · Approval workflow</a></aside>
  <section className="card builder-form"><FormSection title="General details"><div className="form-grid"><Field label="Product name"><input defaultValue="Business Growth"/></Field><Field label="Product code"><input defaultValue="BUS-GROWTH"/></Field><Field label="Currency"><select defaultValue="ZMW"><option>ZMW</option><option>USD</option></select></Field><Field label="Status"><select><option>Draft</option><option>Active</option></select></Field></div></FormSection>
  <FormSection title="Terms & pricing"><div className="form-grid"><Field label="Minimum principal"><input type="number" defaultValue="5000"/></Field><Field label="Maximum principal"><input type="number" defaultValue="100000"/></Field><Field label="Annual interest rate (%)"><input type="number" defaultValue="28"/></Field><Field label="Interest method"><select value={method} onChange={e=>setMethod(e.target.value)}><option value="REDUCING_BALANCE">Reducing balance</option><option value="FLAT">Flat rate</option></select></Field><Field label="Minimum term"><input type="number" defaultValue="3"/></Field><Field label="Maximum term"><input type="number" defaultValue="18"/></Field><Field label="Term unit"><select><option>Months</option><option>Weeks</option><option>Days</option></select></Field><Field label="Repayment frequency"><select><option>Monthly</option><option>Biweekly</option><option>Weekly</option><option>Custom</option></select></Field></div></FormSection>
  <FormSection title="Risk & approval"><div className="form-grid"><Field label="Collateral"><select><option>Optional</option><option>Required</option><option>None</option></select></Field><Field label="Guarantor"><select><option>Required</option><option>Optional</option><option>None</option></select></Field><Field label="Approval workflow"><select><option>Business Credit</option><option>Standard Credit</option><option>Fast Track</option></select></Field><Field label="Arrears tolerance"><input defaultValue="0.00"/></Field></div></FormSection>
  <div className="builder-note"><b>Current calculation method: {method==="REDUCING_BALANCE"?"Reducing balance":"Flat rate"}</b><span>ABC stores product rules separately and snapshots agreed financial terms onto the loan at origination.</span></div>
  </section></div>
 </div></AppShell>
}
function FormSection({title,children}:{title:string;children:React.ReactNode}){return <div className="form-section"><h2>{title}</h2>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
